### ISSUE TITLE
Field 'enabledOnly' in HTML request

### ISSUE THREAD

**Issue by matze-dd** [Findus23/pyLanguagetool#41]
As LT expects 'true' or 'yes', the field should be set in api.py with
```
if enabled_only:
    post_parameters["enabledOnly"]  = 'true'
```
See line 285 in [LT's TextChecker.java](https://github.com/languagetool-org/languagetool/blob/master/languagetool-server/src/main/java/org/languagetool/server/TextChecker.java):
```
    boolean useEnabledOnly = "yes".equals(parameters.get("enabledOnly")) || "true".equals(parameters.get("enabledOnly"));
```

**Comment by Findus23** [comment]
Thanks for reporting. You are right, I never really used that option.
If you want to, you can create a PR, otherwise I'll fix it in the next release.
